In [4]:
jolts = sorted(int(l) for l in """16
10
15
5
1
11
7
19
6
12
4""".splitlines())

In [68]:
jolts = sorted(int(l) for l in open("data/10.txt"))

In [1]:
jolts = sorted(int(l) for l in """28
33
18
42
31
14
46
20
48
47
24
23
49
45
19
38
39
11
1
32
25
35
8
17
7
9
4
2
34
10
3""".splitlines())

In [2]:
jolts = [0] + jolts + [jolts[-1]+3]

In [26]:
import numpy as np

In [27]:
_, c = np.unique(np.diff(jolts), return_counts=True)
c[0]*c[1]

220

In [28]:
gaps = list(np.diff(jolts))

In [74]:
parts = []
while len(gaps)>0:
    i = gaps.index(3)
    parts.append(jolts[:i+1])
    gaps = gaps[i+1:]
    jolts = jolts[i+1:]

In [75]:
[len(p) for p in parts]

[3,
 5,
 4,
 1,
 3,
 5,
 4,
 1,
 4,
 1,
 1,
 4,
 5,
 3,
 1,
 2,
 5,
 1,
 4,
 1,
 4,
 1,
 4,
 5,
 1,
 1,
 1,
 5,
 5,
 5,
 5,
 2,
 5]

In [76]:
parts

[[0, 1, 2],
 [5, 6, 7, 8, 9],
 [12, 13, 14, 15],
 [18],
 [21, 22, 23],
 [26, 27, 28, 29, 30],
 [33, 34, 35, 36],
 [39],
 [42, 43, 44, 45],
 [48],
 [51],
 [54, 55, 56, 57],
 [60, 61, 62, 63, 64],
 [67, 68, 69],
 [72],
 [75, 76],
 [79, 80, 81, 82, 83],
 [86],
 [89, 90, 91, 92],
 [95],
 [98, 99, 100, 101],
 [104],
 [107, 108, 109, 110],
 [113, 114, 115, 116, 117],
 [120],
 [123],
 [126],
 [129, 130, 131, 132, 133],
 [136, 137, 138, 139, 140],
 [143, 144, 145, 146, 147],
 [150, 151, 152, 153, 154],
 [157, 158],
 [161, 162, 163, 164, 165]]

In [15]:
lookup = {
    1: 1,
    2: 1,
    3: 2,
    4: 4,
    5: 7,
}

In [78]:
import math

In [79]:
math.prod([lookup[len(p)] for p in parts])

37024595836928

In [13]:
import math
import numpy as np
#def part_2():
jolts = sorted(int(l) for l in open("data/10.txt"))
jolts = [0] + jolts + [jolts[-1]+3]
gaps = list(np.diff(jolts))
parts = []
while len(gaps)>0:
    i = gaps.index(3)
    parts.append(jolts[:i+1])
    gaps = gaps[i+1:]
    jolts = jolts[i+1:]
#return math.prod([lookup[len(p)] for p in parts])

In [36]:
last = jolts[0]
parts = [[last]]
for i in range(1, len(jolts)):
    if jolts[i]-3 == last:
        parts.append([jolts[i]])
    else:
        parts[-1].append(jolts[i])
    last = jolts[i]
parts

[[0, 1, 2, 3, 4],
 [7, 8, 9, 10, 11],
 [14],
 [17, 18, 19, 20],
 [23, 24, 25],
 [28],
 [31, 32, 33, 34, 35],
 [38, 39],
 [42],
 [45, 46, 47, 48, 49],
 [52]]

In [5]:
jolts

[0,
 1,
 2,
 3,
 4,
 7,
 8,
 9,
 10,
 11,
 14,
 17,
 18,
 19,
 20,
 23,
 24,
 25,
 28,
 31,
 32,
 33,
 34,
 35,
 38,
 39,
 42,
 45,
 46,
 47,
 48,
 49,
 52]

In [6]:
import numpy as np
np.split(jolts, np.where(np.diff([-1] + jolts) == 3)[0])


[array([0, 1, 2, 3, 4]),
 array([ 7,  8,  9, 10, 11]),
 array([14]),
 array([17, 18, 19, 20]),
 array([23, 24, 25]),
 array([28]),
 array([31, 32, 33, 34, 35]),
 array([38, 39]),
 array([42]),
 array([45, 46, 47, 48, 49]),
 array([52])]